### ISSUE TITLE
Quick help link to guide does not work properly

### ISSUE THREAD

**Issue by gitjoost** [omz/Dash-Plugin-for-Xcode#43]
If one brings up the "quick help" inspector in Xcode, it presents help text as well as three links at the bottom: a) a declared in link, b) a link to reference of the relevant class and c) a link to a guide document. For example the quick help text on NSUserDefaults displays:
Declared in: NSUserDefaults.h
Reference: NSUserDefaults Class Reference
Guides: Preferences and settings programming guide.

Clicking the first link shows the header file in Xcode, the second the class definition in Dash. The Guides link however does not link to a guide. Instead, it brings up Dash with the same information as for the reference link - the NSUserDefaults class in this case.

**Comment by Kapeli** [comment]
This happens because the plugin is not able to convert the file URL to a Dash URL at https://github.com/omz/Dash-Plugin-for-Xcode/blob/master/Classes/OMQuickHelpPlugin.m#L211-L221. I'm not really sure how to fix it...

The URL looks something like this:
```
file:///Applications/Xcode.app/Contents/Developer/Documentation/DocSets/com.apple.adc.documentation.OSX.docset/Contents/Resources/Documents/documentation/Cocoa/Conceptual/URLLoadingSystem/index.html
```

To convert it, we need a way to get the name and the type of the entry, not just the URL.

**Comment by Kapeli** [comment]
Reference-style integration has been disabled as there's no way to get the names reliably. Sorry!
