### ISSUE TITLE
Dash looses filter on search

### ISSUE THREAD

**Issue by sebastianludwig** [omz/Dash-Plugin-for-Xcode#47]
When I set a scope in Dash (`ios:` for example) and **option+click** a symbol in Xcode, Dash opens but the scope is gone. This is annoying because some symbols also exist in other docsets so the result list is unnecessarily long and cluttered.

**Comment by Kapeli** [comment]
This is by design. Keyword filters are not meant to be persistent and plugins always overwrite them.

You have two alternatives:
1. Use search profiles instead of keywords. Search profiles are persistent. See https://kapeli.com/dash_guide#searchProfiles for more details.
2. Enable platform detection for the plugin, so that it will use `ios:` itself when needed. See https://github.com/omz/Dash-Plugin-for-Xcode#automatic-platform-detection for more details.

**Comment by sebastianludwig** [comment]
Oh, RTFM - thanks!
